# Generated by Django 2.0.4 on 2018-04-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersform',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='usersform',
            table='website_database',
        ),
    ]
