# Generated by Django 2.0.4 on 2018-04-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180409_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usersform',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterModelTable(
            name='usersform',
            table='website_contact_database',
        ),
    ]
